[google_service_account]
type = "service_account"
project_id = "my-project-443812"
private_key_id = "0e493da89e966e66386c13b41aadce94f5a36522"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5cNsQ9h88i9P1
w9kh5c9DiWgtWKLbSpDFqFcFwlJDidQICxJU/uJBxt1vruJEUfecLbEz0vlJgM+l
UIUiKzjm/akKvnQuX3bSuvZR8YpUqwfdcRD9dw3BKKiPLZsuvX0mKVNKRAi1yHtW
4/QGqs5Q+BBQFNvjK2vrD0+zp91UcFtJ8/gUkDudL9Thzkro2+ZjOiAGiME4RU8X
OhUCp33aclxoN+4+vf4BsqRbMcxfwrD249yRb+07aJ4Ru0TXffMflEN2ftdtgvT6
el7uu6YRh4Rq98bnQ/eHHIr6oVEpydTmqve/SSDItrw5mcO0scAbq1CLZsqA0Z+r
eOL8wn5jAgMBAAECggEAK7zoFoCOjofGZw2Z7YpYD+xdU3C3/LQCIHSbjeKu53of
NgRyfvSdJfmDKf/cI1QX7FDEnl4Q6RrGHw42UIBUS/shP0T7fyKKEpsBVQN85opu
cPbllHrblicCVr7hfq030uPlXrtcOJAAM1bRrC7mOafApTq+QD7yFb+HQ28A35S3
jQ6QcUZIDwW9aRxoRS49WniMA9kFZb8gpTT5Gdbz60bawZMkBjhvNofx8BidevCK
51Nnf5TYoKe0x+GjLJCs5Fq8K9I7TriBmumPOkM0yfWBZSRANwSGy7GNuUtyua6G
cxRC1c5ytGv0bnDrIHeIP+MAUsJh7DJIu1K8GS98FQKBgQDqa3+acV+vVmgfnKxn
kmOT8wLfK1/3NCEHYh3UGf+rLBTCEr8mtOqBWsQN35s6y6Y4cXpyYROr/8hSkf4+
JYqG9gxC2S8petooPq8a1e3lwtthYCCQHphVeIhQLvtL8N9y3gKYj9AwVzN0+Z0t
gzkem3V80e1RoBmNHImGxedylQKBgQDKgxUnSx60pgMmCCGGkR0/4sxqQv3GVcgK
2tXpXhvugC3jdmf3xJQwmAHmKv2Uho4inl1rO4aCFGDIUEY80rqIydHspgyPzGOE
ddoWFWbDLZG9fiofmf77aT1Ib7qn3v2TWjQHRpIyBV8gfUiNqF0m1LHel8SzMI8M
/ew2/linFwKBgDKVq91p5ZnybVmU92cKIc7FO7NoqravWwk61PD2A0OuqXQPk4wI
sinjqjbML7UKSP4ZDrEr3ZDaCyI2OsSyWSgyZAbw0sqCphzVGfgSfdl8qNZkZeJz
l6+p6NBUswl6Gt2wpqLBNc2Yo5P0YUR28pZ2OW4L5sgcYicfJ1Yb0ovZAoGAD2XO
GvG8QPIKdT7TBb9M4Qmmj0HOt+DX1/Nxpk/Qgd7fHldnalBZECTOqCiGpV9huUIf
SkL5ZDSWc0SfQoqnQjVOL9ckR168BltLnLg92wNA/I52N3bnC0iiLzrHj3IGB8kp
AZCdFw6PgBHmjVbK1mP/rjQN8a30goFgD4JhTTsCgYEApnvoV6Ron+jFhpHyb39h
PohWmPHLRm5QHKKNnRzAxyl4m+bam9V3KQcka4FUmNPwger78jleUm5ePhUyNPA8
UZyFd40bgiocon5477eJWJTqtbQbhHqvgfz58CoNCtm23z9OblM+humQsRHQ51Zx
Hf1ptF6Rzm9tm5+Z+89yfKQ=
-----END PRIVATE KEY-----"""
client_email = "logs-844@my-project-443812.iam.gserviceaccount.com"
client_id = "114573790431186993605"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/logs-844%40my-project-443812.iam.gserviceaccount.com"

