[google_service_account]
type = "service_account"
project_id = "my-project-443812"
private_key_id = "0e493da89e966e66386c13b41aadce94f5a36522"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5cNsQ9h88i9P1
w9kh5c9DiWgtWKLbSpDFqFcFwlJDidQICxJU/uJBxt1vruJEUfecLbEz0vlJgM+l
UIUiKzjm/akKvnQuX3bSuvZR8YpUqwfdcRD9dw3BKKiPLZsuvX0mKVNKRAi1yHtW
-----END PRIVATE KEY-----"""
client_email = "logs-844@my-project-443812.iam.gserviceaccount.com"
client_id = "114573790431186993605"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/logs-844%40my-project-443812.iam.gserviceaccount.com"
